export const WORLDORBIT_HELP_TITLE = "WorldOrbit Quick Start";

export function buildSolarSystemExampleBlock(): string {
  return [
    "```worldorbit",
    "schema 2.5",
    "",
    "system Sol",
    '  title "Solar System"',
    "  referencePlane ecliptic",
    "",
    "defaults",
    "  view orthographic",
    "  preset atlas-card",
    "",
    'group inner-system',
    '  label "Inner System"',
    "",
    "object star Sun",
    "  mass 1sol",
    "",
    "object planet Mercury",
    "  orbit Sun",
    "  semiMajor 0.39au",
    "  color #b7b1a7",
    "  groups inner-system",
    "",
    "object planet Venus",
    "  orbit Sun",
    "  semiMajor 0.72au",
    "  color #d9b37a",
    "  groups inner-system",
    "",
    "object planet Earth",
    "  orbit Sun",
    "  semiMajor 1au",
    "  color #6fa8ff",
    "  atmosphere nitrogen-oxygen",
    "  groups inner-system",
    "",
    "object moon Luna",
    "  orbit Earth",
    "  distance 384400km",
    "",
    "object planet Mars",
    "  orbit Sun",
    "  semiMajor 1.52au",
    "  color #d97c52",
    "  groups inner-system",
    "```",
  ].join("\n");
}

export function getQuickStartMarkdown(): string {
  return [
    "Paste this into a note:",
    "",
    "```worldorbit",
    "schema 2.5",
    "",
    "system Sol",
    "",
    "object star Sun",
    "",
    "object planet Earth",
    "  orbit Sun",
    "  semiMajor 1au",
    "```",
    "",
    "Useful fields:",
    "- `object planet NAME` creates a body",
    "- `orbit TARGET` places it around another object",
    "- `semiMajor 1au` or `distance 384400km` controls placement",
    "- `color #6fa8ff` sets a display color hint",
    "- `radius`, `mass`, `kind`, and `atmosphere` add more detail",
    "",
    "Locked mode keeps scrolling safe in notes. Activate interaction only when you want to pan or zoom the diagram.",
  ].join("\n");
}
